spring:
  profiles:
    active: development
  application:
    name: where-is-my-money
  thymeleaf:
    cache: false
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    defer-datasource-initialization: true
  datasource:
    url: ${DATASOURCE_URL:jdbc:postgresql://localhost:5432/where-is-my-money}
    username: ${DATASOURCE_USER:postgres}
    password: ${DATASOURCE_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver
  sql:
    init:
      mode: always
app:
  base-url: http://localhost:8080/
verification:
  code-length: 4
  code-expiration-minutes: 1m